version: 2
jobs:
  project_test:
    working_directory: ~/repository
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - restore_cache:
          key: node_modules-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: 'yarn'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: 'yarn test'
workflows:
  version: 2
  test:
    jobs:
      - project_test